export const users = [
  {
    id: 1,
    firstName: "Neil",
    lastName: "Sims",
    username: "neil.sims@flowbite.com",
    gradeLevel: "Senior Highschool",
    status: "pending",
    gender: "Male",
  },
  {
    id: 2,
    firstName: "John Carlo",
    lastName: "Abanes",
    username: "john.carlo@flowbite.com",
    gradeLevel: "Senior Highschool",
    status: "approved",
    gender: "Male",
  },
  {
    id: 3,
    firstName: "Cris Carlo",
    lastName: "Abanes",
    username: "cris.carlo@flowbite.com",
    gradeLevel: "Senior Highschool",
    status: "pending",
    gender: "Male",
  },
  {
    id: 4,
    firstName: "John Carlo",
    lastName: "Abanes",
    username: "john.carlo@flowbite.com",
    gradeLevel: "Senior Highschool",
    status: "approved",
    gender: "Male",
  },
  {
    id: 5,
    firstName: "John Carlo",
    lastName: "Abanes",
    username: "john.carlo@flowbite.com",
    gradeLevel: "Senior Highschool",
    status: "approved",
    gender: "Male",
  },
  {
    id: 6,
    firstName: "John Carlo",
    lastName: "Abanes",
    username: "john.carlo@flowbite.com",
    gradeLevel: "Junior Highschool",
    status: "approved",
    gender: "Male",
  },
];

export const admins = [
  {
    firstName: "Alexander",
    lastName: "Lee",
    username: "alexander@example.com",
    password: "",
    confirmPassword: "",
    subject: "Mathematics",
    employeeNumber: "EMP001",
    position: "Professor",
    gender: "Male",
  },
  {
    firstName: "Elizabeth",
    lastName: "Clark",
    username: "elizabeth@example.com",
    password: "",
    confirmPassword: "",
    subject: "Economics",
    employeeNumber: "EMP002",
    position: "Lecturer",
    gender: "Female",
  },
  {
    firstName: "Amelia",
    lastName: "Grant",
    username: "amelia@example.com",
    password: "",
    confirmPassword: "",
    subject: "History",
    employeeNumber: "EMP003",
    position: "Senior Lecturer",
    gender: "Female",
  },
  {
    firstName: "Amelia",
    lastName: "Grant",
    username: "amelia@example.com",
    password: "",
    confirmPassword: "",
    subject: "History",
    employeeNumber: "EMP003",
    position: "Senior Lecturer",
    gender: "Female",
  },
  {
    firstName: "Amelia",
    lastName: "Grant",
    username: "amelia@example.com",
    password: "",
    confirmPassword: "",
    subject: "History",
    employeeNumber: "EMP003",
    position: "Senior Lecturer",
    gender: "Female",
  },
];

